# Eat Safe, Love

## Notebook Set Up

In [135]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [136]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)
print(mongo.list_database_names())

['admin', 'autosaurus', 'classDB', 'config', 'epa', 'fruits_db', 'gardenDB', 'local', 'met', 'rop', 'travel_db', 'uk_food']

In [137]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [138]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [139]:
# assign the collection to a variable
establishments = db['establishments']
pprint(establishments.find_one())

{'AddressLine1': 'The Pines Garden',
 'AddressLine2': 'Beach Road',
 'AddressLine3': 'St Margarets Bay',
 'AddressLine4': 'Kent',
 'BusinessName': 'The Pines Calyx',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4587.362402580997,
 'FHRSID': 254250,
 'LocalAuthorityBusinessID': 'PI/000066174',
 'LocalAuthorityCode': '182',
 'LocalAuthorityEmailAddress': 'publicprotection@dover.gov.uk',
 'LocalAuthorityName': 'Dover',
 'LocalAuthorityWebSite': 'http://www.dover.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT15 6DZ',
 'RatingDate': '2021-08-17T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('640cbedae7d1f12c242991bf'),
 'geocode': {'latitude': '51.148133', 'longitude': '1.383298'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/254250',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [140]:
# Find the establishments with a hygiene score of 20
query ={'scores.Hygiene': 20}
results = establishments.find(query)  
# Use count_documents to display the number of documents in the result
print(establishments.count_documents(query))
# Display the first document in the results using pprint
hygiene = list(results)
pprint(hygiene[0])

41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('640cbedae7d1f12c2429afd8'),
 'geocode': {'latitude': '50.769705', 'longitude': '0.27694'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [141]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.json_normalize(hygiene)

# Display the number of rows in the DataFrame
print(f"The number of rows {len(hygiene_df['_id'])}")

# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

The number of rows 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,640cbedae7d1f12c2429afd8,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.27694,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,640cbedae7d1f12c2429b359,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,640cbedae7d1f12c2429b666,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.15927,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,640cbedae7d1f12c2429b84f,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.10202,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,640cbedae7d1f12c2429b860,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,640cbedae7d1f12c2429c1fe,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,640cbedae7d1f12c2429c41b,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.7121671,51.5350065,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,640cbedae7d1f12c2429d961,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,640cbedae7d1f12c2429dd8f,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146449998021126,51.1859474182129,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,640cbedae7d1f12c2429e5b5,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.57005,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [142]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query ={'RatingValue': {'$gte': '4'}}
results = establishments.find(query)
# Use count_documents to display the number of documents in the result
print(establishments.count_documents(query))
# Display the first document in the results using pprint
RatingValue = list(results)
print(RatingValue[0])

36292
{'_id': ObjectId('640cbedae7d1f12c242991bf'), 'FHRSID': 254250, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000066174', 'BusinessName': 'The Pines Calyx', 'BusinessType': 'Other catering premises', 'BusinessTypeID': 7841, 'AddressLine1': 'The Pines Garden', 'AddressLine2': 'Beach Road', 'AddressLine3': 'St Margarets Bay', 'AddressLine4': 'Kent', 'PostCode': 'CT15 6DZ', 'Phone': '', 'RatingValue': '5', 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-08-17T00:00:00', 'LocalAuthorityCode': '182', 'LocalAuthorityName': 'Dover', 'LocalAuthorityWebSite': 'http://www.dover.gov.uk/', 'LocalAuthorityEmailAddress': 'publicprotection@dover.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': '1.383298', 'latitude': '51.148133'}, 'RightToReply': '', 'Distance': 4587.362402580997, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'https://api.ratings.food.gov.uk/establishments/254250'}]}

In [143]:
# Convert the result to a Pandas DataFrame
RatingValue_df = pd.json_normalize(RatingValue)

# Display the number of rows in the DataFrame
print(f"The number of rows {len(RatingValue_df['_id'])}")

# Display the first 10 rows of the DataFrame
RatingValue_df.head(10)

The number of rows 36292

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,640cbedae7d1f12c242991bf,254250,0,PI/000066174,The Pines Calyx,Other catering premises,7841,The Pines Garden,Beach Road,St Margarets Bay,...,1.383298,51.148133,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,640cbedae7d1f12c242991c0,1034540,0,PI/000078691,The Coastguard Inn,Pub/bar/nightclub,7843,The Bay,St Margarets Bay,Kent,...,1.387974,51.152225,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,640cbedae7d1f12c242991c1,1290215,0,PI/000083029,FirstLight Bar & Café,Restaurant/Cafe/Canteen,1,1 The Droveway,St Margarets Bay,Kent,...,1.378231,51.150625,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,640cbedae7d1f12c242991c2,551803,0,PI/000070948,The Tea Room,Restaurant/Cafe/Canteen,1,The Pines Garden,Beach Road,St Margarets Bay,...,1.383298,51.148133,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,640cbedae7d1f12c242991c3,632212,0,PI/000043474,Lenox House,Hotel/bed & breakfast/guest house,7842,27 Granville Road,St Margarets Bay,Kent,...,1.385585,51.152411,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,640cbedae7d1f12c242991c4,429982,0,PI/000043978,The Barn,Restaurant/Cafe/Canteen,1,Reach Court Farm,Reach Road,St Margarets At Cliffe,...,1.371115,51.147379,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,640cbedae7d1f12c242991c5,1273080,0,PI/000082753,Lovetocater,Restaurant/Cafe/Canteen,1,Walmer And Kingsdown Golf Club,The Leas,Kingsdown,...,1.4032986,51.1787284,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,640cbedae7d1f12c242991c6,1531040,0,PI/000085904,The Halfway Hut,Restaurant/Cafe/Canteen,1,Walmer And Kingsdown Golf Club,The Leas,Kingsdown,...,1.4032986,51.1787284,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,640cbedae7d1f12c242991c7,1030622,0,PI/000078259,Portal House School,School/college/university,7845,Sea Street,St Margarets At Cliffe,Kent,...,1.375095,51.152913,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,640cbedae7d1f12c242991c8,574015,0,PI/000069596,St Margarets At Cliffe Nursery And After Schoo...,Caring Premises,5,St Margarets At Cliffe C P School,Sea Street,St Margarets At Cliffe,...,1.375095,51.152913,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [144]:
#Add new restaurant to the collection
new_bussiness = {
    "BusinessName":"Penang Flavours",
    "BusinessType":"Restaurant/Cafe/Canteen",
    "BusinessTypeID":"",
    "AddressLine1":"Penang Flavours",
    "AddressLine2":"146A Plumstead Rd",
    "AddressLine3":"London",
    "AddressLine4":"",
    "PostCode":"SE18 7DY",
    "Phone":"",
    "LocalAuthorityCode":"511",
    "LocalAuthorityName":"Greenwich",
    "LocalAuthorityWebSite":"http://www.royalgreenwich.gov.uk",
    "LocalAuthorityEmailAddress":"health@royalgreenwich.gov.uk",
    "scores":{
        "Hygiene":"",
        "Structural":"",
        "ConfidenceInManagement":""
    },
    "SchemeType":"FHRS",
    "geocode":{
        "longitude":"0.08384000",
        "latitude":"51.49014200"
    },
    "RightToReply":"",
    "Distance":4623.9723280747176,
    "NewRatingPending":True
}
establishments.insert_one(new_bussiness)

In [147]:
establishments.find_one()

{'_id': ObjectId('640cbedae7d1f12c242991bf'),
 'FHRSID': 254250,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000066174',
 'BusinessName': 'The Pines Calyx',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'AddressLine1': 'The Pines Garden',
 'AddressLine2': 'Beach Road',
 'AddressLine3': 'St Margarets Bay',
 'AddressLine4': 'Kent',
 'PostCode': 'CT15 6DZ',
 'Phone': '',
 'RatingValue': '5',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2021-08-17T00:00:00',
 'LocalAuthorityCode': '182',
 'LocalAuthorityName': 'Dover',
 'LocalAuthorityWebSite': 'http://www.dover.gov.uk/',
 'LocalAuthorityEmailAddress': 'publicprotection@dover.gov.uk',
 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': 1.383298, 'latitude': 51.148133},
 'RightToReply': '',
 'Distance': 4587.362402580997,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/254250'}]}

In [146]:
establishments.update_many({},[{'$set':{'geocode.longitude':{'$toDouble':'$geocode.longitude'}}}])
establishments.update_many({},[{'$set':{'geocode.latitude':{'$toDouble':'$geocode.latitude'}}}])

In [ ]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score


degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {'RatingValue':{'$eq': '5'}}
sort =  [('scores.Hygiene', -1)]

# Print the results

In [ ]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [178]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
match_query = {'$match':{'scores.Hygiene':{'$eq': 0}}}
group_query = {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}}
sort_values = {"$sort":{'count': -1} } 

pipeline = [match_query,group_query,sort_values]
# Print the number of documents in the result
results = list(establishments.aggregate(pipeline))
print("Number of documents in results: ", len(results))
# Print the first 10 results
pprint(results[0:10])

Number of documents in results:  56
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [179]:
# Convert the result to a Pandas DataFrame

No_Hygiene_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print("Number of rows in the DF: ", len(No_Hygiene_df['_id']))
# Display the first 10 rows of the DataFrame
No_Hygiene_df.head(10)

Number of rows in the DF:  56

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542